services:
    form.type.dynamic_entity:
        class: Hvanoch\Bundle\DynamicFormBundle\Form\DynamicEntityType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
          - { name: form.type, alias: dynamic_entity }